apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: mongodb
  name: clusterRoleBinding-mongodb
  namespace: database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: clusterRole-mongodb
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
